version: "3.8"
services:
  ran-1:
    container_name: ran-1
    hostname: ran-1
    build:
      context: ./dockertest
    image: deb-test-gtp 
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - .:/volume
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      net1:
        ipv4_address: 10.0.10.2
        ipv6_address: fd00:d0cc:e700:1111:1::2
  ran-2:
    container_name: ran-2
    hostname: ran-2
    build:
      context: ./dockertest
    image: deb-test-gtp 
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - .:/volume
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      net1:
        ipv4_address: 10.0.10.4
        ipv6_address: fd00:d0cc:e700:1111:1::4
  upf-1:
    container_name: upf-1 
    hostname: upf-1 
    build:
      context: ./dockertest
    image: deb-test-gtp 
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - .:/volume
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    networks:
      net1:
        ipv4_address: 10.0.10.3
        ipv6_address: fd00:d0cc:e700:1111:1::3
      net2:
        ipv4_address: 10.0.20.3
        ipv6_address: fd00:d0cc:e700:1111:2::3
      dn2:
        ipv4_address: 10.0.50.3
        ipv6_address: fd00:d0cc:e700:1111:5::3
  upf-2:
    container_name: upf-2
    hostname: upf-2
    build:
      context: ./dockertest
    image: deb-test-gtp 
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - .:/volume
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    networks:
      net2:
        ipv4_address: 10.0.20.2
        ipv6_address: fd00:d0cc:e700:1111:2::2
      dn1:
        ipv4_address: 10.0.40.3
        ipv6_address: fd00:d0cc:e700:1111:4::3
  target-1:
    container_name: target-1
    hostname: target-1
    build:
      context: ./dockertest
    image: deb-test-gtp 
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - .:/volume
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      dn1:
        ipv4_address: 10.0.40.2
        ipv6_address: fd00:d0cc:e700:1111:4::2
  target-2:
    container_name: target-2
    hostname: target-2
    build:
      context: ./dockertest
    image: deb-test-gtp 
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - .:/volume
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      dn2:
        ipv4_address: 10.0.50.2
        ipv6_address: fd00:d0cc:e700:1111:5::2
   




         
networks:
  net1:
    name: net1
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net1
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
        - subnet: fd00:d0cc:e700:1111:1::/80
  net2:
    name: net2
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net2
    ipam:
      driver: default
      config:
        - subnet: 10.0.20.0/24
        - subnet: fd00:d0cc:e700:1111:2::/80
  dn1:
    name: dn1 
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dn1 
    ipam:
      driver: default
      config:
        - subnet: 10.0.40.0/24
        - subnet: fd00:d0cc:e700:1111:4::/80
  dn2:
    name: dn2 
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dn2
    ipam:
      driver: default
      config:
        - subnet: 10.0.50.0/24
        - subnet: fd00:d0cc:e700:1111:5::/80
