gtpu-entities:
  - "10.0.10.3" 
  - "10.0.20.3" 
  - "10.0.30.3" 
pfcp-sessions:
  - pdrs:
      - id: 1
        precedence: 255
        pdi:
          sourceInterface: "Access"
          fteid:
            teid: 1
            ipAddress: "10.0.10.3"
        outerHeaderRemoval:
          description: 0
          extensionHeaderDeletion: 0
        farid: 1
      - id: 2
        precedence: 255
        pdi:
          sourceInterface: "Access"
          fteid:
            teid: 3
            ipAddress: "10.0.10.3"
        outerHeaderRemoval:
          description: 0
          extensionHeaderDeletion: 0
        farid: 2
    fars:
      - id: 1
        forwardingParameters:
          destinationInterface: "Core"
          outerHeaderCreation:
            teid: 2
            gtpuPeer: "10.0.20.2"
      - id: 2
        forwardingParameters:
          destinationInterface: "Core"
          outerHeaderCreation:
            teid: 4
            gtpuPeer: "10.0.30.2"
