gtpu-entities:
  - "10.0.10.3" 
  - "10.0.20.3" 
  - "10.0.30.3" 
dnn_list:
  - dnn: "sliceA"
    cidr: "10.0.200.0/24"
pfcp-sessions:
  - pdrs:
      - id: 1
        precedence: 255
        pdi:
          sourceInterface: "Access"
          fteid:
            teid: 1
            ipAddress: "10.0.10.3"
        outerHeaderRemoval:
          description: 0
          extensionHeaderDeletion: 0
        farid: 1
      - id: 3
        precedence: 254
        pdi:
          sourceInterface: "Access"
          sdf-filter:
            description: "permit out ip from 10.0.200.1 to 10.0.40.0/24"
          fteid:
            teid: 1
            ipAddress: "10.0.10.3"
        outerHeaderRemoval:
          description: 0
          extensionHeaderDeletion: 0
        farid: 1
      - id: 2
        precedence: 255
        pdi:
          sourceInterface: "Access"
          fteid:
            teid: 3
            ipAddress: "10.0.10.3"
        outerHeaderRemoval:
          description: 0
          extensionHeaderDeletion: 0
        farid: 2
      - id: 3
        precedence: 255
        pdi:
          sourceInterface: "Core"
          fteid:
            teid: 5
            ipAddress: "10.0.20.3"
        farid: 3
        outerHeaderRemoval:
          description: 0
          extensionHeaderDeletion: 0
    fars:
      - id: 1
        forwardingParameters:
          destinationInterface: "Core"
          outerHeaderCreation:
            teid: 2
            gtpuPeer: "10.0.20.2"
      - id: 2
        forwardingParameters:
          destinationInterface: "Core"
          outerHeaderCreation:
            teid: 4
            gtpuPeer: "10.0.30.2"
      - id: 3
        forwardingParameters:
          destinationInterface: "Access"
          outerHeaderCreation:
            teid: 6
            gtpuPeer: "10.0.10.2"
