entities:
  - ipAddress: "10.0.10.3" 
    pdrs:
      - teid: 1
        far:
          - teid: 2
            gtpuPeer: "10.0.20.2"
      - teid: 3
        far:
          - teid: 4
            gtpuPeer: "10.0.30.2"

  - ipAddress: "10.0.20.3" 
  - ipAddress: "10.0.30.3" 
ipEndpoints:
