entities:
  - ipAddress: "10.0.10.3" 
    pdrs:
      - id: 1
        teid: 1
        farid: 1
      - id: 2
        teid: 3
        farid: 2
    fars:
      - id: 1
        teid: 2
        gtpuPeer: "10.0.20.2"
      - id: 2
        teid: 4
        gtpuPeer: "10.0.30.2"

  - ipAddress: "10.0.20.3" 
  - ipAddress: "10.0.30.3" 
ipEndpoints:
