gtpu-entities:
  - "10.0.20.2"
dnn_list:
  - dnn: "sliceA"
    cidr: "10.0.200.0/24"
pfcp-sessions:
  - pdrs:
    - id: 1
      precedence: 255
      pdi:
        sourceInterface: "Access"
        fteid:
          teid: 2
          ipAddress: "10.0.20.2"
      farid: 1
      outerHeaderRemoval:
        description: 0
        extensionHeaderDeletion: 0
    - id: 2
      precedence: 255
      pdi:
        sourceInterface: "Core"
      farid: 2

    fars:
      - id: 1
        forwardingParameters:
          destinationInterface: "Core"
      - id: 2
        forwardingParameters:
          destinationInterface: "Access"
          outerHeaderCreation:
            teid: 5
            gtpuPeer: "10.0.20.3"

